
package com.demo.ws.client.jws.client;

import com.demo.ws.server.jws.HelloJwsService;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloJwsServiceImplService", targetNamespace = "http://jws.server.ws.demo.com/", wsdlLocation = "http://localhost:8088/service/helloJwsService?wsdl")
public class HelloJwsServiceImplService
    extends Service
{

    private final static URL HELLOJWSSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOJWSSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HELLOJWSSERVICEIMPLSERVICE_QNAME = new QName("http://jws.server.ws.demo.com/", "HelloJwsServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8088/service/helloJwsService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOJWSSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HELLOJWSSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HelloJwsServiceImplService() {
        super(__getWsdlLocation(), HELLOJWSSERVICEIMPLSERVICE_QNAME);
    }

    public HelloJwsServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOJWSSERVICEIMPLSERVICE_QNAME, features);
    }

    public HelloJwsServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOJWSSERVICEIMPLSERVICE_QNAME);
    }

    public HelloJwsServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOJWSSERVICEIMPLSERVICE_QNAME, features);
    }

    public HelloJwsServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloJwsServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloJwsService
     */
    @WebEndpoint(name = "HelloJwsServiceImplPort")
    public com.demo.ws.server.jws.HelloJwsService getHelloJwsServiceImplPort() {
        return super.getPort(new QName("http://jws.server.ws.demo.com/", "HelloJwsServiceImplPort"), com.demo.ws.server.jws.HelloJwsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloJwsService
     */
    @WebEndpoint(name = "HelloJwsServiceImplPort")
    public com.demo.ws.server.jws.HelloJwsService getHelloJwsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://jws.server.ws.demo.com/", "HelloJwsServiceImplPort"), HelloJwsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOJWSSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOJWSSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HELLOJWSSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
